<?php
/*
Plugin Name: Menu Simple Apunts Informatica
Plugin URI: http://www.apunts.es
Description: Plugin per ocultar les entrades del menu que no volem utilitzar (modificar les entrades en el ficher custom.css)
Author: Roman Ribes
Version: 0.1
$Id:  $
*/ //Funcio principal del pluginfunction add_my_stylesheet() {
    wp_enqueue_style( 'myCSS', plugins_url( '/styles/custom.css', __FILE__ ) );
}
add_action('admin_print_styles', 'add_my_stylesheet');//Link de pàgina de ajustes en menuadd_action( 'admin_menu', 'Ap_add_admin_menu' );add_action( 'admin_init', 'Ap_settings_init' );function Ap_add_admin_menu(){ 	add_options_page( 'MenuSimple', 'MenuSimple', 'manage_options', 'menusimple', 'ap_options_page' );}function Ap_settings_init(){ 	register_setting( 'pluginPage', 'Ap_settings' );	add_settings_section(		'Ap_pluginPage_section', 		__( 'Menu Simple Apunts Informatica', 'wordpress' ), 		'Ap_settings_section_callback', 		'pluginPage'	);	add_settings_field( 		'Ap_checkbox_field_1', 		__( 'Settings field description', 'wordpress' ), 		'Ap_checkbox_field_1_render', 		'pluginPage', 		'Ap_pluginPage_section' 	);	add_settings_field( 		'Ap_checkbox_field_2', 		__( 'Settings field description', 'wordpress' ), 		'Ap_checkbox_field_2_render', 		'pluginPage', 		'Ap_pluginPage_section' 	);	add_settings_field( 		'Ap_checkbox_field_3', 		__( 'Settings field description', 'wordpress' ), 		'Ap_checkbox_field_3_render', 		'pluginPage', 		'Ap_pluginPage_section' 	);}function Ap_checkbox_field_1_render(  ) { 	$options = get_option( 'Ap_settings' );	?>	<input type='checkbox' name='Ap_settings[Ap_checkbox_field_1]' <?php checked( $options['Ap_checkbox_field_1'], 1 ); ?> value='1'>	<?php}function Ap_checkbox_field_2_render(  ) { 	$options = get_option( 'Ap_settings' );	?>	<input type='checkbox' name='Ap_settings[Ap_checkbox_field_2]' <?php checked( $options['Ap_checkbox_field_2'], 1 ); ?> value='1'>	<?php}function Ap_checkbox_field_3_render(  ) { 	$options = get_option( 'Ap_settings' );	?>	<input type='checkbox' name='Ap_settings[Ap_checkbox_field_3]' <?php checked( $options['Ap_checkbox_field_3'], 1 ); ?> value='1'>	<?php}function Ap_settings_section_callback(  ) { 	echo __( '<p>Página de ajustes del plugin para ocultar las entradas del menu que no queremos mostrar.</p>', 'wordpress' );}function Ap_options_page(  ) { 	?>	<form action='options.php' method='post'>				<?php		settings_fields( 'pluginPage' );		do_settings_sections( 'pluginPage' );		submit_button();		?>			</form>	<?php}function plugin_add_settings_link( $links ) {    $settings_link = '<a href="options-general.php?page=menusimple">' . __( 'Settings' ) . '</a>';    array_push( $links, $settings_link );  	return $links;}$plugin = plugin_basename( __FILE__ );add_filter( "plugin_action_links_$plugin", 'plugin_add_settings_link' );?>